logstash_version: "1.5"
logstash_defaults: |
        LS_USER=root
        LS_GROUP=root
        LS_HEAP_SIZE="256m"

logstash_inputs: |
  file {
    path => ["/var/log/syslog"]
    start_position => "beginning"
    codec => "plain"
    type => "system"
  }
  file {
    path => ["/var/log/dmesg"]
    start_position => "beginning"
    codec => "plain"
    type => "system"
  }
  file {
    path => ["/var/log/auth.log"]
    start_position => "beginning"
    codec => "plain"
    type => "auth"
  }
  syslog {
    facility_labels => ["security/authorization"]
    type => "auth"
  }
logstash_filters: |

logstash_outputs: |
   if [type] == "auth" {
     elasticsearch {
      document_type => "auth"
      host => "127.0.0.1"
      cluster => "ansible-es"
      protocol => "http"
     }
    } else {
      elasticsearch {
        document_type => "system"
        host => "127.0.0.1"
        cluster => "ansible-es"
        protocol => "http"
      }
    }   
 
 

